production:
      adapter: postgresql
      database: fibonacci_prime_production
      pool: 5
      timeout: 5000
test:
      adapter: postgresql
      encoding: unicode
      database: fibonacci_prime_test
      pool: 5
      username: fibonacci_prime
      password:

development:
      adapter: postgresql
      encoding: unicode
      database: fibonacci_prime_development
      pool: 5
      username: fibonacci_prime
      password:
